
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class symd {
  /* terminals */
  public static final int fli = 3;
  public static final int cade = 14;
  public static final int idva = 11;
  public static final int verd = 9;
  public static final int fpr = 5;
  public static final int nume = 13;
  public static final int EOF = 0;
  public static final int may = 7;
  public static final int ili = 2;
  public static final int error = 1;
  public static final int men = 8;
  public static final int deci = 12;
  public static final int fals = 10;
  public static final int ipr = 4;
  public static final int dia = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ili",
  "fli",
  "ipr",
  "fpr",
  "dia",
  "may",
  "men",
  "verd",
  "fals",
  "idva",
  "deci",
  "nume",
  "cade"
  };
}

