
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140808 (SVN rev 54)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class symf {
  /* terminals */
  public static final int ipa = 12;
  public static final int ccnu = 62;
  public static final int crep = 66;
  public static final int ico = 14;
  public static final int acar = 69;
  public static final int dete = 27;
  public static final int nulo = 71;
  public static final int cima = 65;
  public static final int fpa = 13;
  public static final int ccte = 60;
  public static final int fco = 15;
  public static final int mini = 39;
  public static final int fin = 16;
  public static final int cate = 61;
  public static final int div = 5;
  public static final int may = 8;
  public static final int mas = 2;
  public static final int filt = 41;
  public static final int map = 49;
  public static final int dop = 24;
  public static final int desc = 34;
  public static final int sino = 48;
  public static final int caso = 31;
  public static final int com = 23;
  public static final int cvid = 67;
  public static final int pyc = 17;
  public static final int asce = 35;
  public static final int acli = 68;
  public static final int defe = 32;
  public static final int igu = 6;
  public static final int or = 19;
  public static final int opet = 54;
  public static final int reto = 28;
  public static final int acer = 70;
  public static final int cdes = 63;
  public static final int fals = 47;
  public static final int lgxm = 53;
  public static final int impr = 25;
  public static final int impo = 26;
  public static final int and = 20;
  public static final int ill = 10;
  public static final int men = 3;
  public static final int inve = 37;
  public static final int func = 33;
  public static final int EOF = 0;
  public static final int fll = 11;
  public static final int busc = 40;
  public static final int todo = 51;
  public static final int error = 1;
  public static final int maxi = 38;
  public static final int sele = 30;
  public static final int cade = 43;
  public static final int si = 29;
  public static final int cada = 36;
  public static final int algu = 52;
  public static final int opid = 55;
  public static final int deci = 44;
  public static final int pot = 7;
  public static final int por = 4;
  public static final int cbot = 64;
  public static final int ccon = 58;
  public static final int verd = 46;
  public static final int cven = 57;
  public static final int pun = 22;
  public static final int not = 18;
  public static final int ctex = 59;
  public static final int nos = 9;
  public static final int idva = 42;
  public static final int opno = 56;
  public static final int var = 21;
  public static final int redu = 50;
  public static final int nume = 45;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "men",
  "por",
  "div",
  "igu",
  "pot",
  "may",
  "nos",
  "ill",
  "fll",
  "ipa",
  "fpa",
  "ico",
  "fco",
  "fin",
  "pyc",
  "not",
  "or",
  "and",
  "var",
  "pun",
  "com",
  "dop",
  "impr",
  "impo",
  "dete",
  "reto",
  "si",
  "sele",
  "caso",
  "defe",
  "func",
  "desc",
  "asce",
  "cada",
  "inve",
  "maxi",
  "mini",
  "busc",
  "filt",
  "idva",
  "cade",
  "deci",
  "nume",
  "verd",
  "fals",
  "sino",
  "map",
  "redu",
  "todo",
  "algu",
  "lgxm",
  "opet",
  "opid",
  "opno",
  "cven",
  "ccon",
  "ctex",
  "ccte",
  "cate",
  "ccnu",
  "cdes",
  "cbot",
  "cima",
  "crep",
  "cvid",
  "acli",
  "acar",
  "acer",
  "nulo"
  };
}

