/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;
import java.io.File;
import javazoom.jlgui.basicplayer.BasicPlayer;
/**
 *
 * @author sergi
 */
public class Musica extends javax.swing.JPanel {

    private BasicPlayer player;
    int iniciado=0;
    boolean auto;
    /**
     * Creates new form Musica
     * @param ruta
     * @param x
     * @param y
     * @param auto
     * @param alto
     * @param ancho
     */
    public Musica(String ruta,int x,int y,boolean auto,int alto,int ancho) {
        initComponents();
        player = new BasicPlayer();
        this.setBounds(x, y, ancho, alto);
          try{
                AbrirFichero(ruta);
            }catch(Exception e){
                
            }
         this.auto = auto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reproducir = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        reproducir.setBackground(new java.awt.Color(51, 255, 0));
        reproducir.setText("Reproducir");
        reproducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reproducirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reproducir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reproducir)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reproducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reproducirActionPerformed
        // TODO add your handling code here:
        if(iniciado==0){
           reproducir.setText("pausar");
           iniciado=1;
           try{
                Play();
            }catch(Exception e){
                
            }
        }else if(iniciado==1){
            reproducir.setText("reproducir");
            iniciado=2;
            try{
                Pausa();
            }catch(Exception e){
                
            }
        }else{
            reproducir.setText("pausar");
           iniciado=1;
           try{
                Continuar();
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_reproducirActionPerformed
public void Play() throws Exception {
  player.play();
}
 
public void AbrirFichero(String ruta) throws Exception {
  File archivo = new File(ruta);
  player.open(archivo);
}
 
public void Pausa() throws Exception {
  player.pause();
}
 
public void Continuar() throws Exception {
  player.resume();
}
 
public void Stop() throws Exception {
  player.stop();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton reproducir;
    // End of variables declaration//GEN-END:variables
}
