/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.media.CannotRealizeException;
import javax.media.Manager;
import javax.media.NoPlayerException;
import javax.media.Player;

/**
 *
 * @author sergi
 */
public class Video extends javax.swing.JPanel {

    private Player mediaPlayer;
    private Component controls;

    /**
     * Creates new form Video
     *
     * @param ruta
     * @param x
     * @param y
     * @param auto
     * @param alto
     * @param ancho
     */
    public Video(String ruta, int x, int y, boolean auto, int alto, int ancho) {
        initComponents();
        this.setBounds(x, y, ancho, alto);
        try {
            mediaPlayer = Manager.createRealizedPlayer(new File(ruta).toURI().toURL());
            Component video2 = mediaPlayer.getVisualComponent();
            video2.setSize(ancho, alto - 24);
            video2.setVisible(true);
            controls = mediaPlayer.getControlPanelComponent();
            controls.setSize(ancho, 24);
            if (video2 != null) {
                add(video2); //agrega el componente del reproductor al panel 
            }
            mediaPlayer.start();
        } catch (IOException ex) {
            Logger.getLogger(Video.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoPlayerException ex) {
            Logger.getLogger(Video.class.getName()).log(Level.SEVERE, null, ex);
        } catch (CannotRealizeException ex) {
            Logger.getLogger(Video.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
