/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import java.awt.BorderLayout;
import java.awt.Canvas;
import java.awt.Component;
import uk.co.caprica.vlcj.binding.LibVlc;
import uk.co.caprica.vlcj.player.MediaPlayerFactory;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;
import uk.co.caprica.vlcj.player.embedded.videosurface.CanvasVideoSurface;
import uk.co.caprica.vlcj.player.embedded.windows.Win32FullScreenStrategy;
import uk.co.caprica.vlcj.runtime.RuntimeUtil;

/**
 *
 * @author sergi
 */
public class Video extends javax.swing.JPanel {

    String ruta;
    int x, y;
    int alto, ancho;
    Videoview nuevo;
    boolean entro = true;
    boolean auto;

    /**
     * Creates new form Video
     *
     * @param ruta
     * @param x
     * @param y
     * @param auto
     * @param alto
     * @param ancho
     */
    public Video(String ruta, int x, int y, boolean auto, int alto, int ancho) {
        initComponents();
        this.setLocation(x, y);
        this.setSize(ancho, 25);
        this.x = x;
        this.y = y;
        this.ruta = ruta.replace("/", "\\\\");
        this.alto = alto;
        this.ancho = ancho;
        this.auto = auto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Stop = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        Stop.setBackground(new java.awt.Color(153, 255, 204));
        Stop.setText("Reproducir");
        Stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Stop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Stop)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void StopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopActionPerformed
        // TODO add your handling code here:
        if (entro) {
            nuevo = new Videoview(ruta, x, y, alto, ancho);
            entro = false;
        } else {
            nuevo.cerrar();
            entro = true;
        }
    }//GEN-LAST:event_StopActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Stop;
    // End of variables declaration//GEN-END:variables

    void inicializar() {
        if(auto){
        nuevo = new Videoview(ruta, x, y, alto, ancho);
        entro = false;
        }
    }

    void finalizar() {
        if(!entro){
            nuevo.cerrar();
            entro = true;
        }
    }
}
